NAME_MAIN = 'Main'
NAME_SLEEP = 'Sleep'
NAME_SEND = 'Send'
NAME_WITHDRAW = 'Withdraw'
ERROR_AMOUNT_LESS_OR_EQUAL_TO_ZERO = 'amount <= 0'
ERROR_GAS_REQUIRED_EXCEEDS_ALLOWANCE = 'gas required exceeds allowance'
ERROR_INTRINSIC_GAS_TOO_LOW = 'intrinsic gas too low'
